### PR TITLE
Adding a comparision of Xalgo/Interlibr to existing rule categories

### PR DESCRIPTION
**Pull request by karfai**
Connects to #41

### CODE REVIEW

**Comment by jpotvin** [comment]
I'll need to work through the text. There are several phrases such as:
" received in a fashion similar to (but not the same as) events"
"bears a resemblance to the staged architecture of... because of the shared architectural pattern and nothing more"
" Semantic resemblance is misleading in this case, the processing pipeline is not intended to be either of these categories."
" bear a superficial resemblance to "
" loosely matches an inference system"
"At the time the language was designed, it was simpler to"
" it is most likely that it represents a complex transformative rule system"
"Xalgo likely represents a transformative rules system but considering it as such is not useful and may be detrimental."

All these ought to be refined to more definitive statements, but I'll need to co-write as a think it through. 

***
Also, your use of the word "effective", I still think that should be "in effect".  "Effectiveness" is a qualitative concept with gradients -- less or more effective. "In effect" is binary -- Is or Is not.
Then I'm reminded that "in effect" has two common meanings -- also used as "What that meant, in effect, is that the aircraft overshot the runway."
So from this online dictionary...
https://www.macmillandictionary.com/dictionary/british/in-effect
I see we might want to use the word "operating".  Look for the rules that are operating for the given general context. Then look for the rules that are applicable to the particular circumstances.

**Comment by karfai** [comment]
*In effect*... Yeah, it's more grammatically correct, but it's not one word. I'm using *effective* because it's one decent word.

**Comment by karfai** [comment]
> All these ought to be refined to more definitive statements, but I'll need to co-write as a think it through.

There's a reason that I'm writing it this way. I'm trying to solve the consistent problem of generalities vs. specifics when talking about how software works. We *generalize* to broaden the scope of a solution **but** that generalization can enter imprecision once expressed in an inexact language (english).

**Comment by wolders** [comment]
Change label from Effective to InEffect. Its shorter and has the exact
meaning. I also had to tumble Effective in my mind as i was reading.

William Olders
613-762-9383

**Pull request merged**
